### ISSUE TITLE
Issue: Admin can add category.

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#1]
## ⚙️ Feature

> Admin can add category

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> #####

<img width="778" alt="Screen Shot 2021-11-03 at 11 04 12 AM" src="https://user-images.githubusercontent.com/39370528/140167067-bde98e60-3050-474e-ae44-3c664047bb57.png">
!-- drag and drop your screenshots below this line -->

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to  file to create the post request for adding data to category DB
- [x] Update `server/index.js` to  file to create the get request for getting data from category DB
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to Redirect component
- [x] Create a component to navBar component
- [x] Create home page
- [x] create admin-menu page
- [x] Create a library folder add app-context, decode-token, parse-route component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
