### ISSUE TITLE
Feature: User can create customer waitlist

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#12]
## ⚙️ Feature

> ##### User can create customer waitlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Admin will able to create customer waiting list and storing there data to database
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="789" alt="Screen Shot 2021-11-05 at 11 32 53 AM" src="https://user-images.githubusercontent.com/39370528/140561366-415e6b1f-08a5-4ab6-9f15-add8be4d4913.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle post request to store user data
- [x] insert post data to users table
- [x] insert post data to waitlist table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a page for the waitlist
- [x] Create form to get customer name and mobile number
- [x] Create a component to list data from the waitlist table
- [x] Update component to once data is loaded

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
