### ISSUE TITLE
Issue : Admin can login

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#14]
## ⚙️ Feature

> ##### admin can login 

## 📐 Functionality

> ##### Admin will able to login 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="536" alt="Screen Shot 2021-11-08 at 10 07 16 AM" src="https://user-images.githubusercontent.com/39370528/140794858-277383d7-913a-4495-8dfb-2556a54ba47e.png">
<img width="247" alt="Screen Shot 2021-11-08 at 10 06 58 AM" src="https://user-images.githubusercontent.com/39370528/140794860-74009c8b-08c7-46f8-8c31-f4949b059ec3.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update index.js to handle post request for login
- [x] generate token
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to login user 
- [x] set state of user
- [x] store generated token to local storage

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
