### ISSUE TITLE
Issue: Customer can login

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#16]
## ⚙️ Feature

> ##### Customer can login

## 📐 Functionality

> ##### Customer will able to login

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="536" alt="Screen Shot 2021-11-08 at 10 07 16 AM" src="https://user-images.githubusercontent.com/39370528/140809591-a0967ece-5822-411c-88c4-0a661b624383.png">
<img width="247" alt="Screen Shot 2021-11-08 at 10 06 58 AM" src="https://user-images.githubusercontent.com/39370528/140809595-b17da7fd-9131-4eaf-964a-999f58c2441c.png">
 applicable -->

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update index.js to handle customer login
- [x] generate token
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for customer login
- [x] Store user info into local storge
- [x] Update user state
- [x] Restrict customer from accessing add-menu, waitlist, add category page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
