### ISSUE TITLE
Issue: Admin can assign table

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#18]
## ⚙️ Feature

> ##### Admin can assign table

## 📐 Functionality

> ##### Admin will be able to assign a table to the customer 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="897" alt="Screen Shot 2021-11-08 at 1 31 56 PM" src="https://user-images.githubusercontent.com/39370528/140821443-5cf80a0d-32fa-4df4-813c-8ba688d3c548.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update index.js to handle post request to allocate table.
- [x] Update index.js to handle get request to get tables information.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show table status
- [x] get table numbers from the database 
- [x] render multiple div base on table number
- [x] create modal to assign table
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
