### ISSUE TITLE
Issue: Customer can view menu

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#2]
## ⚙️ Feature

> ##### Admin can create waiting list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="630" alt="Screen Shot 2021-11-09 at 1 16 51 PM" src="https://user-images.githubusercontent.com/39370528/141006243-39b73f9f-2692-4db9-9ff3-ad3d18d4d87f.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get request to fetch category and items from database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to view the menu fetched from the database
- [x] Update component when menu is fetched
- [x] set state for menuFetch and empty array and isLodding to true
- [x] create modalto show item

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
