### ISSUE TITLE
Issue: Customer can view cart

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#4]
## ⚙️ Feature

> ##### Customer can view and order from menu.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="793" alt="Screen Shot 2021-11-10 at 11 02 40 AM" src="https://user-images.githubusercontent.com/39370528/141176778-0c5b8435-a08b-40ec-931d-5fe1c1f0f337.png">
<img width="281" alt="Screen Shot 2021-11-09 at 11 44 17 PM" src="https://user-images.githubusercontent.com/39370528/141176781-b941ac4d-06ba-451f-805e-e0a135137e6a.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get request to display item added to cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to view item added to cart
- [x] Update component to once data is fetch
- [x] add note textarea for description

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
