### ISSUE TITLE
Issue: Admin can view orders

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#5]
## ⚙️ Feature

> ##### Admin can view orders

## 📐 Functionality

> ##### Admin can view orders placed by customers

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="583" alt="Screen Shot 2021-11-10 at 5 30 32 PM" src="https://user-images.githubusercontent.com/39370528/141220738-5a16834f-462d-4396-b2a8-4e9ae5adaf10.png">
<img width="278" alt="Screen Shot 2021-11-10 at 5 30 11 PM" src="https://user-images.githubusercontent.com/39370528/141220743-684a9cf8-a9cc-4a8a-9f8a-7bbb219134c6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get request to display customers order
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to list customer orders
- [x] Restrict customer from accessing order page
- [x] add order div on home page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
