### ISSUE TITLE
Issue: Admin can change order status

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#6]
## ⚙️ Feature

> ##### Admin can change order status

## 📐 Functionality

> ##### Admin can change customer order status 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="271" alt="Screen Shot 2021-11-12 at 12 31 55 PM" src="https://user-images.githubusercontent.com/39370528/141530852-d4959f5a-90a0-4e81-b841-9c9c53fb6613.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to handle post request to change status of the order
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a modal to display order
- [ ] Add button to change the status of the order
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
