### ISSUE TITLE
Issue: Admin can add items

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/final-project#8]
## ⚙️ Feature

> ##### Admin can add items

## 📐 Functionality

> ##### User can add food item add store it to the database

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for 

<img width="227" alt="Screen Shot 2021-11-03 at 11 33 09 AM" src="https://user-images.githubusercontent.com/39370528/140171561-8dc360f1-aa0e-44a5-9186-b8d6bb5e61eb.png">
<img width="252" alt="Screen Shot 2021-11-03 at 11 32 36 AM" src="https://user-images.githubusercontent.com/39370528/140171583-b618c300-faf3-487d-9fd1-14164691ab65.png">
<img width="762" alt="Screen Shot 2021-11-03 at 11 32 47 AM" src="https://user-images.githubusercontent.com/39370528/140171590-59f6d9a7-d0de-4b85-96b2-0d9cd427c75c.png">

### ☁️ Server

- [x] Update `server/index.js` to create post request and store item data
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to add from
- [x] Create a component to get list of category from database 
- [x] Update form component to render fetch category list 
- [x] add input type file for image upload

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
